Remove deprecated warnings in jsonSerialize functions (#27)
integral-learning/moodle-auth_mumie pull request #29
Opened 2024-01-23 14:45 UTC by voegii

This solves #27

2024-02-07 17:14 UTC, Lyannic commented
Thanks for you contribution. Unfortunately, the Moodle codechecker fails with the following error
```
 FILE: /home/runner/work/moodle-auth_mumie/moodle-auth_mumie/moodle/auth/mumie/classes/mumie_tag.php
------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
------------------------------------------------------------------------------------------------------------------------------
 61 | ERROR | Inline doc block comments are not allowed; use "// Comment." instead
    |       | (moodle.Commenting.InlineComment.DocBlock)
------------------------------------------------------------------------------------------------------------------------------
```

Apparently, it recognizes the PHP 8 attribute `#[\ReturnTypeWillChange]` as an inline doc clock comment. Currently, I am not sure how we can fix this.

2024-04-30 11:18 UTC, Lyannic commented
This seems to work fine. However, I think that it might be better, to not disable the rule for the whole file, but only for the line that requires it. We have only one line per file that we actually want to ignore.

I suggest using `// phpcs:ignore moodle.Commenting.InlineComment.DocBlock` above the `#[\ReturnTypeWillChange]` line.
See the [CodeSniffer docs](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#ignoring-parts-of-a-file) at `Again, you can selectively ignore one or more specific error message codes, sniffs, categories of sniffs, or entire standards.`.

2024-05-01 07:23 UTC, voegii commented
Ok, I've moved it above the `#[\ReturnTypeWillChange]`. But before doc block. Otherwise there is the error "MissingDocBlock".

2024-05-06 15:21 UTC, Lyannic requested changes
Unfortunately, the pipeline now fails, as you can see
```
/home/runner/work/moodle-auth_mumie/moodle-auth_mumie/moodle/auth/mumie/classes/mumie_tag.php
    Line 67: Function mumie_tag::jsonSerialize is not documented
/home/runner/work/moodle-auth_mumie/moodle-auth_mumie/moodle/auth/mumie/classes/mumie_course.php
    Line 199: Function mumie_course::jsonSerialize is not documented
```

I can't remember, whether we ran the pipeline for your previous version.

2025-02-20 13:12 UTC, closed without merging

2025-02-20 13:12 UTC, voegii commented
This is solved in commit 9c18e8e.

Thank you.